[package]
name = "service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.25"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full", "test-util"] }
